name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --frozen-lockfile
      - name: Build
        uses: borales/actions-yarn@v5
        with:
          cmd: build
